### ISSUE TITLE
Cluster install step failed while running `oc login` command

### ISSUE THREAD

**Issue by chetna14manku** [RedHatQE/openshift-cli-installer#233]
After OSD cluster is created successfully, `oc login` command is failing

**Comment by chetna14manku** [comment]
Noticed all the latest jobs failing at cluster install while running `oc login` command.
This is the [PR](https://github.com/RedHatQE/openshift-cli-installer/pull/230) that added the `oc login` command.
[periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-rosa-rhods-addon-baseline-fips/1711290401303826432/artifacts/smoke-rosa-rhods-addon-baseline-fips/cluster-install/)
[periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-rhods-addon-baseline-fips
](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-interop-v4.13-IIB-smoke-osd-rhods-addon-baseline-fips/1711290402515980288/artifacts/smoke-osd-rhods-addon-baseline-fips/cluster-install/)

**Comment by ascerra** [comment]
As you mentioned in the previous title of this issue there seems to be oc login being called somewhere 
- It doesn't appear to be part of the [cluster step](https://steps.ci.openshift.org/reference/cluster-install) that runs this automation from what I can tell.
- We just need to make sure that when we call oc login that we never print the command itself to output as it exposes the cluster password.
